### ISSUE TITLE
ECMAScript module (instead of CommonJS)

### ISSUE THREAD

**Issue by gcerquant** [kievsash/ngx-markjs#14]
With Angular 10, I get a new warning message when including CommonJS dependencies:

>Warning: /path/src/app/app.module.ts depends on 'ngx-markjs'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

This warning is helpful, as this has a real impact on the [size of the app](https://web.dev/commonjs-larger-bundles/).

**Could you package ngx-markjs as an ECMAScript module (ESM) bundle?**

**Comment by kievsash** [comment]
Hi
Sorry, busy as of now.
Feel free to fork and provide fix you need and publish as your own.

**Comment by gcerquant** [comment]
Thank you for the reply. 
I understand. I will have a look, if I manage to find how I will send a PR. 

Thank you for your library, it is useful to me.

**Comment by kievsash** [comment]
Just released Angular 14 ver. Can you check if it still shows the warning?
