### ISSUE TITLE
Update When Content Updates?

### ISSUE THREAD

**Issue by queejie** [kievsash/ngx-markjs#2]
Thank you for this module. An issue I'm having is that the highlight is only working for static text.  If I have an element whose text is populated from a database (for example), the highlighting does not take effect.

![image](https://user-images.githubusercontent.com/1616827/71380086-fc396580-259b-11ea-97f5-7d51604723a3.png)

Any ideas?  Thanks in advance.

**Comment by kievsash** [comment]
Hi!
Thanks for reporting that.
Seems like mark.js starts and holds the inner text before value is applied by angular
I think I have to add some update() method to directive to recreate Mark.js instance 
So developer can trigger it after value is applied by Angular (at least with setTimeout to wait until text is inserted).
Hm, have to check it.
Will try to take a look in the coming days

**Comment by queejie** [comment]
Thanks!

Sent from my iPhone

On Dec 24, 2019, at 5:29 AM, Oleksandr <notifications@github.com> wrote:

﻿

Hi!
Thanks for reporting that.
Seems like mark.js starts and holds the inner text before value is applied by angular
I think I have to add some update() method to directive to recreate Mark.js instance
So developer can trigger it after value is applied by Angular (at least with setTimeout to wait until text is inserted).
Hm, have to check it.
Will try to take a look in the coming days

**Comment by kievsash** [comment]
Hi @queejie 
TBH I cannot reproduce it
Here is what I did (gif link): https://ibb.co/K6Cmjq1
Can you create some playground with reproducing plz?
