### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by yoat** [kievsash/ngx-markjs#3]
I'm using Angular 8.
I installed ngx-markjs with the command line from the readme, and imported in my app.module as described.

I get this error:
```
ERROR in ./node_modules/ngx-markjs/fesm2015/ngx-markjs.js
Module not found: Error: Can't resolve 'mark.js' in '[Path to my project]\node_modules\ngx-markjs\fesm2015'
```

Is there any other information I can provide? I followed all instructions provided with the supported Angular app and it was not successful.

**Comment by kievsash** [comment]
Hi!
Thanks for reporting
Try to install markjs separately also
npm i markjs

**Comment by yoat** [comment]
Thanks, that did work. The mark.js package name has a dot:

> npm i mark.js --save

If requiring mark.js separately is on purpose (to enable version independence?) could you update the README to say so? Much appreciated!

**Comment by kievsash** [comment]
You are right, I will update!
Thanks for reporting
