### ISSUE TITLE
Ivy distribution

### ISSUE THREAD

**Issue by hetalishah** [kievsash/ngx-markjs#44]
Could you please publish an Ivy distribution?

Thank you

**Comment by kievsash** [comment]
Good idea!
Let me fibd some time for it

**Comment by kievsash** [comment]
Dear @hetalishah 
Just published Ivy compatible ngx-markjs 14.0.0, based on Angular 14
plz check if it works as intended if you have time

**Comment by hetalishah** [comment]
Thank you. I will take a look and let you know :)
